services:
  - type: web
    name: shitster-web
    runtime: python
    buildCommand: apt-get install -y fonts-dejavu fonts-liberation && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SPOTIFY_CLIENT_ID
        value: 5839ffa0907243398d394ddb8b1f6acd
      - key: SPOTIFY_CLIENT_SECRET
        sync: false   # wird im Render Dashboard eingetragen
      - key: REDIRECT_URI
        value: https://shitster-web.onrender.com/callback
      - key: SECRET_KEY
        generateValue: true
